# Generated by Django 2.2.6 on 2019-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('url', models.CharField(max_length=300, verbose_name='url')),
                ('img', models.CharField(max_length=300, verbose_name='img src')),
            ],
        ),
    ]
