# Generated by Django 2.1 on 2019-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191023_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
