# Generated by Django 2.1 on 2019-10-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191023_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
